Repository woozlabs/echo-be, pull requests merged in 2024-08, with the labels that each got.

#101 [FEAT] Verification gemini & ChatGPT Setting 및 초안 설계 구현
  src/main/java/woozlabs/echo/domain/chatGPT/ChatGPTInterface.java
  src/main/java/woozlabs/echo/domain/chatGPT/controller/ChatGptController.java
  src/main/java/woozlabs/echo/domain/chatGPT/dto/ChatGPTRequest.java
  src/main/java/woozlabs/echo/domain/chatGPT/dto/ChatGPTResponse.java
  src/main/java/woozlabs/echo/domain/chatGPT/service/ChatGptService.java
  src/main/java/woozlabs/echo/domain/gemini/controller/GeminiController.java
  src/main/java/woozlabs/echo/domain/gemini/prompt/VerificationMailPrompt.java
  src/main/java/woozlabs/echo/domain/gemini/service/GeminiService.java
  src/main/java/woozlabs/echo/domain/member/service/TokenSchedulerService.java
  src/main/java/woozlabs/echo/global/config/RestTemplateConfig.java
  src/main/java/woozlabs/echo/global/exception/ErrorCode.java
Labels: enhancement

#103 [REFACTOR] 중복 시간 검사 로직 수정
  src/main/java/woozlabs/echo/domain/member/service/TokenSchedulerService.java
Labels: enhancement

#104 [Style]: 인증 메일 확인 기능 주석처리
  build.gradle
  src/main/java/woozlabs/echo/domain/gemini/service/GeminiService.java
  src/main/java/woozlabs/echo/domain/gmail/controller/GmailController.java
  src/main/java/woozlabs/echo/domain/gmail/dto/draft/GmailDraftSendResponse.java
  src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadGetMessages.java
  src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadTotalCountResponse.java
  src/main/java/woozlabs/echo/domain/gmail/service/AsyncGmailService.java
  src/main/java/woozlabs/echo/domain/gmail/service/GmailService.java
  src/main/java/woozlabs/echo/domain/gmail/util/GmailUtility.java
  src/main/java/woozlabs/echo/global/exception/ErrorCode.java
  src/main/resources/keywords_en.txt
  src/main/resources/keywords_ko.txt
Labels: bug

#107 [FEAT] Auth Custom Claims 적용
  src/main/java/woozlabs/echo/domain/member/service/AuthService.java
  src/main/java/woozlabs/echo/global/exception/ErrorCode.java
Labels: enhancement

#109 [STYLE] Claims Key 명칭 superAccountUids -> accounts
  src/main/java/woozlabs/echo/domain/member/service/AuthService.java
Labels: enhancement

#106 [Feat]: 인증 메일 링크 추출 기능 GPT 연동 성공
  build.gradle
  src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadGetMessages.java
  src/main/java/woozlabs/echo/domain/gmail/service/GmailService.java
  src/main/java/woozlabs/echo/domain/gmail/util/GmailUtility.java
  src/main/java/woozlabs/echo/global/exception/ErrorCode.java
  src/main/resources/keywords_en.txt
Labels: enhancement

#113 [Fix]: 요일 데이터가 없는 Timezone 버그 해결 & [Refactor]: 비동기 처리 불필요로 인해 동기+멀티쓰레드 방식으로 변경
  src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadGetMessages.java
  src/main/java/woozlabs/echo/domain/gmail/service/AsyncGmailService.java
  src/main/java/woozlabs/echo/domain/gmail/service/GmailService.java
  src/main/java/woozlabs/echo/domain/gmail/util/GmailUtility.java
  src/main/java/woozlabs/echo/global/constant/GlobalConstant.java
Labels: bug, enhancement

#108 [FEAT] Team, Invitation
  build.gradle
  src/main/java/woozlabs/echo/domain/member/entity/Member.java
  src/main/java/woozlabs/echo/domain/signature/Signature.java
  src/main/java/woozlabs/echo/domain/team/controller/TeamController.java
  src/main/java/woozlabs/echo/domain/team/dto/CreateTeamRequestDto.java
  src/main/java/woozlabs/echo/domain/team/dto/SendInvitationEmailDto.java
  src/main/java/woozlabs/echo/domain/team/dto/TeamInvitationRequestDto.java
  src/main/java/woozlabs/echo/domain/team/dto/TeamMemberDto.java
  src/main/java/woozlabs/echo/domain/team/dto/TeamResponseDto.java
  src/main/java/woozlabs/echo/domain/team/entity/PrivateComment.java
  src/main/java/woozlabs/echo/domain/team/entity/Role.java
  src/main/java/woozlabs/echo/domain/team/entity/SharedEmail.java
  src/main/java/woozlabs/echo/domain/team/entity/Team.java
  src/main/java/woozlabs/echo/domain/team/entity/TeamInvitation.java
  src/main/java/woozlabs/echo/domain/team/entity/TeamMember.java
  src/main/java/woozlabs/echo/domain/team/repository/SharedEmailRepository.java
  src/main/java/woozlabs/echo/domain/team/repository/TeamInvitationRepository.java
  src/main/java/woozlabs/echo/domain/team/repository/TeamRepository.java
  src/main/java/woozlabs/echo/domain/team/service/EmailService.java
  src/main/java/woozlabs/echo/domain/team/service/SharedEmailService.java
  src/main/java/woozlabs/echo/domain/team/service/TeamService.java
  src/main/java/woozlabs/echo/global/config/MongoConfig.java
  src/main/java/woozlabs/echo/global/constant/GlobalConstant.java
  src/main/java/woozlabs/echo/global/exception/ErrorCode.java
  src/main/java/woozlabs/echo/global/scheduler/AccessTokenScheduler.java
  src/main/java/woozlabs/echo/global/scheduler/JunkInvitationScheduler.java
  src/main/resources/templates/invite-email.html
Labels: enhancement

#115 [FEAT] Aws SES
  build.gradle
  src/main/java/woozlabs/echo/domain/team/service/EmailService.java
  src/main/java/woozlabs/echo/domain/team/service/TeamService.java
  src/main/java/woozlabs/echo/global/config/AwsSesConfig.java
Labels: enhancement

#121 [FEAT] Thread Summary Prompt & Change Tone
  src/main/java/woozlabs/echo/domain/gemini/controller/GeminiController.java
  src/main/java/woozlabs/echo/domain/gemini/dto/ChangeToneRequest.java
  src/main/java/woozlabs/echo/domain/gemini/dto/GeminiRequest.java
  src/main/java/woozlabs/echo/domain/gemini/prompt/ThreadSummaryPrompt.java
  src/main/java/woozlabs/echo/domain/gemini/service/GeminiService.java
Labels: bug, enhancement

#126 [FEAT] 팀내 기능에 따른 기능 접근 제어 #1
  src/main/java/woozlabs/echo/domain/team/controller/SharedInboxController.java
  src/main/java/woozlabs/echo/domain/team/controller/TeamController.java
  src/main/java/woozlabs/echo/domain/team/entity/Role.java
  src/main/java/woozlabs/echo/domain/team/entity/ShareStatus.java
  src/main/java/woozlabs/echo/domain/team/entity/SharedEmail.java
  src/main/java/woozlabs/echo/domain/team/repository/SharedInboxRepository.java
  src/main/java/woozlabs/echo/domain/team/repository/TeamMemberRepository.java
  src/main/java/woozlabs/echo/domain/team/service/SharedInboxService.java
  src/main/java/woozlabs/echo/domain/team/service/TeamService.java
  src/main/java/woozlabs/echo/domain/team/utils/AuthorizationUtil.java
  src/main/java/woozlabs/echo/global/exception/ErrorCode.java
Labels: enhancement

#129 [FEAT] GEMINI Proofread 추가 사항 구현
  src/main/java/woozlabs/echo/domain/gemini/controller/GeminiController.java
  src/main/java/woozlabs/echo/domain/gemini/dto/ProofreadResponse.java
  src/main/java/woozlabs/echo/domain/gemini/prompt/ProofreadPrompt.java
  src/main/java/woozlabs/echo/domain/gemini/service/GeminiService.java
  src/main/java/woozlabs/echo/global/exception/ErrorCode.java
Labels: enhancement

#131 [FEAT] Private Comments 초안 및 폴더 분리
  src/main/java/woozlabs/echo/domain/gemini/dto/ProofreadResponse.java
  src/main/java/woozlabs/echo/domain/gemini/prompt/ProofreadPrompt.java
  src/main/java/woozlabs/echo/domain/sharedEmail/controller/PrivateCommentController.java
  src/main/java/woozlabs/echo/domain/sharedEmail/controller/SharedInboxController.java
  src/main/java/woozlabs/echo/domain/sharedEmail/dto/PrivateCommentCreateDto.java
  src/main/java/woozlabs/echo/domain/sharedEmail/dto/PrivateCommentResponseDto.java
  src/main/java/woozlabs/echo/domain/sharedEmail/dto/ShareEmailRequestDto.java
  src/main/java/woozlabs/echo/domain/sharedEmail/dto/UserPublicKeyDto.java
  src/main/java/woozlabs/echo/domain/sharedEmail/dto/thread/ThreadExtractVerificationInfo.java
  src/main/java/woozlabs/echo/domain/sharedEmail/dto/thread/ThreadGetBody.java
  src/main/java/woozlabs/echo/domain/sharedEmail/dto/thread/ThreadGetMessages.java
  src/main/java/woozlabs/echo/domain/sharedEmail/dto/thread/ThreadGetMessagesBcc.java
  src/main/java/woozlabs/echo/domain/sharedEmail/dto/thread/ThreadGetMessagesCc.java
  src/main/java/woozlabs/echo/domain/sharedEmail/dto/thread/ThreadGetMessagesFrom.java
  src/main/java/woozlabs/echo/domain/sharedEmail/dto/thread/ThreadGetMessagesTo.java
  src/main/java/woozlabs/echo/domain/sharedEmail/dto/thread/ThreadGetPart.java
  src/main/java/woozlabs/echo/domain/sharedEmail/dto/thread/ThreadGetPayload.java
  src/main/java/woozlabs/echo/domain/sharedEmail/dto/thread/ThreadGetResponse.java
  src/main/java/woozlabs/echo/domain/sharedEmail/entity/PrivateComment.java
  src/main/java/woozlabs/echo/domain/sharedEmail/entity/ShareStatus.java
  src/main/java/woozlabs/echo/domain/sharedEmail/entity/SharedEmail.java
  src/main/java/woozlabs/echo/domain/sharedEmail/entity/Thread.java
  src/main/java/woozlabs/echo/domain/sharedEmail/entity/UserPublicKey.java
  src/main/java/woozlabs/echo/domain/sharedEmail/repository/PrivateCommentRepository.java
  src/main/java/woozlabs/echo/domain/sharedEmail/repository/SharedInboxRepository.java
  src/main/java/woozlabs/echo/domain/sharedEmail/repository/ThreadRepository.java
  src/main/java/woozlabs/echo/domain/sharedEmail/repository/UserPublicKeyRepository.java
  src/main/java/woozlabs/echo/domain/sharedEmail/service/PrivateCommentService.java
  src/main/java/woozlabs/echo/domain/sharedEmail/service/SharedInboxService.java
  src/main/java/woozlabs/echo/domain/team/dto/SendInvitationEmailDto.java
  src/main/java/woozlabs/echo/domain/team/dto/TeamInvitationRequestDto.java
  src/main/java/woozlabs/echo/domain/team/dto/TeamMemberDto.java
  src/main/java/woozlabs/echo/domain/team/entity/ShareStatus.java
  src/main/java/woozlabs/echo/domain/team/entity/TeamInvitation.java
  src/main/java/woozlabs/echo/domain/team/entity/TeamMember.java
  src/main/java/woozlabs/echo/domain/team/entity/TeamMemberRole.java
  src/main/java/woozlabs/echo/domain/team/repository/TeamMemberRepository.java
  src/main/java/woozlabs/echo/domain/team/repository/ThreadRepository.java
  src/main/java/woozlabs/echo/domain/team/service/EmailService.java
  src/main/java/woozlabs/echo/domain/team/service/TeamService.java
  src/main/java/woozlabs/echo/domain/team/utils/AuthorizationUtil.java
  src/main/resources/templates/invite-email.html
  src/test/java/woozlabs/echo/domain/contactGroup/service/ContactGroupServiceTest.java
Labels: enhancement

#137 [REFACTOR] AWS SES 속도 검증, 테스트 코드 및 flyway DB Migration 적용 및 잡무
  build.gradle
  src/main/java/woozlabs/echo/domain/member/controller/MemberController.java
  src/main/java/woozlabs/echo/domain/member/service/MemberService.java
  src/main/java/woozlabs/echo/domain/team/dto/TeamInvitationRequestDto.java
  src/main/java/woozlabs/echo/global/config/AsyncConfig.java
  src/main/java/woozlabs/echo/global/exception/ErrorCode.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/woozlabs/echo/domain/team/service/EmailServiceTest.java
Labels: documentation, enhancement

#138 [CHORE] flyway 프로덕션 전까지 사용 해제
  build.gradle
Labels: wontfix

#142 [REFACTOR/FIX] PubSubService Conflict 수정 및 스케줄러 메서드 명칭 변경
  src/main/java/woozlabs/echo/domain/gmail/entity/VerificationEmail.java
  src/main/java/woozlabs/echo/domain/gmail/service/PubSubService.java
  src/main/java/woozlabs/echo/domain/member/repository/AccountRepository.java
  src/main/java/woozlabs/echo/global/scheduler/AccessTokenScheduler.java
Labels: enhancement

#155 [CHORE, FEAT] GcloudBuild 캐싱 제거 및 로그 추가 및 Preference 업데이트 단일 가능 처리
  cloudbuild.yaml
  src/main/java/woozlabs/echo/domain/member/controller/AccountController.java
  src/main/java/woozlabs/echo/domain/member/dto/AccountProfileResponseDto.java
  src/main/java/woozlabs/echo/domain/member/dto/NotificationDto.java
  src/main/java/woozlabs/echo/domain/member/dto/PreferenceDto.java
  src/main/java/woozlabs/echo/domain/member/service/AccountService.java
  src/main/java/woozlabs/echo/domain/member/service/MemberService.java
Labels: enhancement

#156 [FIX] cloudbuild.yml 오탈자
  cloudbuild.yaml
Labels: enhancement

#157 [REFACTOR] Theme 역직렬화
  src/main/java/woozlabs/echo/domain/member/entity/Theme.java
Labels: enhancement
